server:
  port: 443

eureka:
  client:
    serviceUrl:
      defaultZone: https://bootcamp37-cristianty.azurewebsites.net/eureka

resilience4j:
  instances:
    requestAssignment:
      timeoutDuration: 2s